using System.Text.Json.Nodes;
using Hyprism.Core;
using Hyprism.Theming;

namespace Hyprism.Modules;

/// <summary>
/// Nilesoft Shell: replaces the right-click menu. Lives in Program Files, so writes and (un)registering go through UAC.
/// Explorer loads it, so safe mode watches every change.
/// </summary>
public sealed class NilesoftShell : ModuleBase
{
    public override string Id => "nilesoft";
    public override string Name => "Context Menu";
    public override string Description => "A modern, blurred right-click menu themed with your colors. Powered by Nilesoft Shell.";
    public override string Glyph => "";
    public override ModuleCategory Category => ModuleCategory.Look;
    public override string Repo => "moudey/Shell";
    public override string License => "MIT";
    protected override string WingetId => "Nilesoft.Shell";
    protected override string? ExePath => Sys.FirstExisting(@"%ProgramFiles%\Nilesoft Shell\shell.exe");

    public override IReadOnlyList<SettingDef> Settings { get; } =
    [
        Choice("effect", "Background effect", "acrylic", ["none", "transparent", "blur", "acrylic"], group: "Look"),
        Slider("opacity", "Background opacity", 85, 0, 100, 5, group: "Look"),
        Toggle("palette", "Use theme colors", true, group: "Look"),
        Slider("radius", "Item corner radius", 2, 0, 3, 1, group: "Look"),
        Slider("borderRadius", "Menu corner radius", 8, 0, 16, 1, group: "Look"),
        Text("font", "Font", "Google Sans Flex", group: "Look"),
        Slider("fontSize", "Font size", 13, 9, 18, 1, group: "Look"),
        Choice("view", "Density", "compact", ["auto", "compact", "small", "medium", "large", "wide"], group: "Look"),
    ];

    string? ThemeFile => ExePath is { } exe ? Path.Combine(Path.GetDirectoryName(exe)!, "imports", "theme.nss") : null;

    public override async Task<ModuleStatus> GetStatusAsync(CancellationToken ct = default)
    {
        var s = await base.GetStatusAsync(ct);
        return s with { Running = s.Installed && Store.Config.For(Id).Enabled };
    }

    public override async Task EnableAsync(CancellationToken ct = default)
    {
        var exe = ExePath ?? throw new InvalidOperationException("Install Context Menu first.");
        await Sys.RunElevatedAsync(exe, "-register -treat -restart", ct);
        Store.Config.For(Id).Enabled = true;
        Store.Save();
        SafeMode.Track("Context Menu", Unregister);
    }

    public override Task DisableAsync(CancellationToken ct = default) => Unregister();

    async Task Unregister()
    {
        if (ExePath is { } exe) await Sys.RunElevatedAsync(exe, "-unregister -restart");
        Store.Config.For(Id).Enabled = false;
        Store.Save();
    }

    public override async Task ApplyAsync(JsonObject s, CancellationToken ct = default)
    {
        var path = ThemeFile ?? throw new InvalidOperationException("Install Context Menu first.");
        var p = CurrentPalette;
        int effect = Array.IndexOf(["none", "transparent", "blur", "acrylic"], s.Str(this, "effect"));
        int opacity = (int)s.Num(this, "opacity");
        bool pal = s.Bool(this, "palette");
        string C(Rgb c) => c.Hex;
        var nss = $$"""
            // Generated by Hyprism. Edit from Hyprism > Context Menu.
            theme
            {
            	name = "modern"
            	view = view.{{s.Str(this, "view")}}
            	dark = {{(pal ? (p.IsDark ? "true" : "false") : "default")}}
            	background
            	{
            {{(pal ? $"\t\tcolor = {C(p.Background)}\n" : "")}}		opacity = {{opacity}}
            		effect = {{(effect == 3 && pal ? $"[3, {C(p.Background)}, {opacity}]" : effect.ToString())}}
            	}
            	item
            	{
            		radius = {{(int)s.Num(this, "radius")}}
            {{(pal ? $"\t\ttext {{ normal = {C(p.Foreground)} select = {C(p.Foreground)} normal.disabled = {C(p.Muted)} select.disabled = {C(p.Muted)} }}\n\t\tback {{ select = {C(p.Overlay)} }}\n" : "")}}	}
            	border
            	{
            		enabled = true
            		size = 1
            {{(pal ? $"\t\tcolor = {C(p.Overlay)}\n" : "")}}		radius = {{(int)s.Num(this, "borderRadius")}}
            	}
            	shadow { enabled = true size = 12 opacity = 25 offset = 4 }
            	font { name = "{{s.Str(this, "font")}}" size = {{(int)s.Num(this, "fontSize")}} }
            {{(pal ? $"\tseparator {{ color = {C(p.Overlay)} }}\n\tsymbol {{ normal = {C(p.Accent)} select = {C(p.Accent)} }}\n" : "")}}	image.align = 2
            }

            """;
        if (File.Exists(path) && File.ReadAllText(path) == nss) return;

        // Program Files needs admin: stage in temp, copy elevated.
        Backup.BeforeWrite(Id, path);
        var tmp = Path.Combine(Path.GetTempPath(), "hyprism-theme.nss");
        await File.WriteAllTextAsync(tmp, nss, ct);
        if (await Sys.RunElevatedAsync("cmd.exe", $"/c copy /y \"{tmp}\" \"{path}\"", ct) != 0)
            throw new InvalidOperationException("Copying the theme into Program Files was cancelled.");
        if (Store.Config.For(Id).Enabled)
        {
            await Sys.RestartExplorerAsync();
            SafeMode.Track("Context Menu theme", Unregister);
        }
    }

    public override Task ApplyPaletteAsync(Palette p, CancellationToken ct = default) => Task.CompletedTask; // writing needs UAC: only on explicit Apply

    public override async Task RestoreDefaultsAsync(CancellationToken ct = default)
    {
        // Backup.RestoreOriginal can't write into Program Files without elevation; copy the backup back through UAC.
        if (ThemeFile is { } path)
        {
            var stage = Path.Combine(Path.GetTempPath(), "hyprism-restore-theme.nss");
            File.WriteAllText(stage, "theme\n{\n\tname=\"modern\"\n\tdark=auto\n\tbackground\n\t{\n\t\tcolor=auto\n\t\topacity=auto\n\t\teffect=auto\n\t}\n\timage.align=2\n}\n");
            await Sys.RunElevatedAsync("cmd.exe", $"/c copy /y \"{stage}\" \"{path}\"", ct);
        }
        Store.Config.For(Id).Settings = [];
        Store.Save();
    }
}
