using System.Text;
using System.Text.Json.Nodes;
using Hyprism.Core;

namespace Hyprism.Modules;

/// <summary>PowerToys: Hyprism toggles individual utilities in PowerToys' settings.json.</summary>
public sealed class PowerToys : ModuleBase
{
    public override string Id => "powertoys";
    public override string Name => "PowerToys";
    public override string Description => "FancyZones, Command Palette, Color Picker, Text Extractor, Peek, Always on Top and more.";
    public override string Glyph => "";
    public override ModuleCategory Category => ModuleCategory.Productivity;
    public override string Repo => "microsoft/PowerToys";
    public override string License => "MIT";
    protected override string WingetId => "Microsoft.PowerToys";
    protected override string ProcessName => "PowerToys";
    protected override string? ExePath => Sys.FirstExisting(@"%LocalAppData%\PowerToys\PowerToys.exe", @"%ProgramFiles%\PowerToys\PowerToys.exe");

    // Keys of "enabled" in PowerToys' settings.json (Settings.UI.Library/EnabledModules.cs).
    static readonly (string Key, string Label, bool Default, string Why)[] Utilities =
    [
        ("CmdPal", "Command Palette", true, "Run anything with Win+Alt+Space."),
        ("FancyZones", "FancyZones", false, "Snap layouts. Turn off if you use tiling."),
        ("ColorPicker", "Color Picker", true, "Win+Shift+C picks any color on screen."),
        ("TextExtractor", "Text Extractor", true, "Copy text out of any image or screen region."),
        ("Peek", "Peek", true, "Quick preview of the selected file."),
        ("AlwaysOnTop", "Always on Top", true, "Win+Ctrl+T pins a window."),
        ("PowerRename", "PowerRename", true, "Bulk rename with regex."),
        ("Image Resizer", "Image Resizer", true, "Resize images from the right-click menu."),
        ("Keyboard Manager", "Keyboard Manager", false, "Remap keys and shortcuts."),
        ("MouseWithoutBorders", "Mouse Without Borders", false, "One mouse and keyboard across PCs."),
        ("Awake", "Awake", false, "Keep the PC awake."),
        ("ZoomIt", "ZoomIt", false, "Zoom and annotate for presentations."),
        ("AdvancedPaste", "Advanced Paste", false, "Paste as plain text, Markdown or JSON."),
        ("Workspaces", "Workspaces", false, "Launch a set of apps into a layout."),
    ];

    public override IReadOnlyList<SettingDef> Settings { get; } =
        [.. Utilities.Select(u => Toggle(u.Key, u.Label, u.Default, u.Why, "Utilities"))];

    static string SettingsPath => Path.Combine(Sys.LocalAppData, "Microsoft", "PowerToys", "settings.json");

    public override async Task ApplyAsync(JsonObject s, CancellationToken ct = default)
    {
        if (!File.Exists(SettingsPath)) throw new InvalidOperationException("Start PowerToys once so it creates its settings.");
        var json = Files.ReadJson(SettingsPath);
        var enabled = json["enabled"] as JsonObject ?? (JsonObject)(json["enabled"] = new JsonObject());
        foreach (var u in Utilities) enabled[u.Key] = s.Bool(this, u.Key);
        if (Write(SettingsPath, json)) await RestartIfRunningAsync();
    }
}

/// <summary>Espanso: text expansion. Hyprism keeps its snippets in its own match file.</summary>
public sealed class Espanso : ModuleBase
{
    public override string Id => "espanso";
    public override string Name => "Text Expander";
    public override string Description => "Type a short trigger, get the full text: signatures, dates, emoji, code. Powered by Espanso.";
    public override string Glyph => "";
    public override ModuleCategory Category => ModuleCategory.Productivity;
    public override string Repo => "espanso/espanso";
    public override string License => "GPL-3.0";
    protected override string WingetId => "Espanso.Espanso";
    protected override string ProcessName => "espansod";
    protected override string? ExePath => Sys.FirstExisting(@"%LocalAppData%\Programs\Espanso\espansod.exe", @"%ProgramFiles%\Espanso\espansod.exe");
    protected override string ExeArgs => "launcher";

    public override IReadOnlyList<SettingDef> Settings { get; } =
    [
        Lines("snippets", "Snippets", ":shrug = ¯\\_(ツ)_/¯\n:mail = me@example.com\n:sig = Best regards,\n",
            "One per line: trigger = replacement. Espanso reloads automatically.", "Snippets"),
        Toggle("date", "Add :date and :time", true, group: "Snippets"),
    ];

    public override Task ApplyAsync(JsonObject s, CancellationToken ct = default)
    {
        static string Q(string v) => "\"" + v.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        var y = new StringBuilder("# Generated by Hyprism. Edit from Hyprism > Text Expander.\nmatches:\n");
        foreach (var line in s.Lines(this, "snippets"))
        {
            var parts = line.Split('=', 2, StringSplitOptions.TrimEntries);
            if (parts.Length == 2 && parts[0].Length > 0) y.Append($"  - trigger: {Q(parts[0])}\n    replace: {Q(parts[1])}\n");
        }
        if (s.Bool(this, "date"))
        {
            y.Append("  - trigger: \":date\"\n    replace: \"{{d}}\"\n    vars:\n      - name: d\n        type: date\n        params:\n          format: \"%Y-%m-%d\"\n");
            y.Append("  - trigger: \":time\"\n    replace: \"{{t}}\"\n    vars:\n      - name: t\n        type: date\n        params:\n          format: \"%H:%M\"\n");
        }
        Write(Path.Combine(Sys.RoamingAppData, "espanso", "match", "hyprism.yml"), y.ToString());
        return Task.CompletedTask;
    }
}

/// <summary>Apps Hyprism installs, starts and keeps updated, with no config of their own to manage.</summary>
public abstract class SimpleApp : ModuleBase
{
    public override ModuleCategory Category => ModuleCategory.Productivity;
}

public sealed class ShareX : SimpleApp
{
    public override string Id => "sharex";
    public override string Name => "Screenshots";
    public override string Description => "Screenshots, screen recording, OCR and annotation. Powered by ShareX.";
    public override string Glyph => "";
    public override string Repo => "ShareX/ShareX";
    public override string License => "GPL-3.0";
    protected override string WingetId => "ShareX.ShareX";
    protected override string ProcessName => "ShareX";
    protected override string? ExePath => Sys.FirstExisting(@"%ProgramFiles%\ShareX\ShareX.exe");
    protected override string ExeArgs => "-silent";
}

public sealed class EarTrumpet : SimpleApp
{
    public override string Id => "eartrumpet";
    public override string Name => "Volume Mixer";
    public override string Description => "Per-app volume and output device from the tray. Powered by EarTrumpet.";
    public override string Glyph => "";
    public override string Repo => "File-New-Project/EarTrumpet";
    public override string License => "MIT (with excluded entities)";
    protected override string WingetId => "File-New-Project.EarTrumpet";
    protected override string ProcessName => "EarTrumpet";
    protected override string StartMenuName => "EarTrumpet";
}

public sealed class TwinkleTray : SimpleApp
{
    public override string Id => "twinkletray";
    public override string Name => "Monitor Brightness";
    public override string Description => "Brightness sliders for every monitor, including external ones (DDC/CI). Powered by Twinkle Tray.";
    public override string Glyph => "";
    public override string Repo => "xanderfrangos/twinkle-tray";
    public override string License => "MIT";
    protected override string WingetId => "xanderfrangos.twinkletray";
    protected override string ProcessName => "Twinkle Tray";
    protected override string? ExePath => Sys.FirstExisting(@"%LocalAppData%\Programs\twinkle-tray\Twinkle Tray.exe");
}

public sealed class Ditto : SimpleApp
{
    public override string Id => "ditto";
    public override string Name => "Clipboard History";
    public override string Description => "Searchable clipboard history with pinned clips. Powered by Ditto.";
    public override string Glyph => "";
    public override string Repo => "sabrogden/Ditto";
    public override string License => "GPL-3.0";
    protected override string WingetId => "Ditto.Ditto";
    protected override string ProcessName => "Ditto";
    protected override string? ExePath => Sys.FirstExisting(@"%ProgramFiles%\Ditto\Ditto.exe");
}

public sealed class QuickLook : SimpleApp
{
    public override string Id => "quicklook";
    public override string Name => "Quick Look";
    public override string Description => "Press Space in Explorer to preview any file, macOS-style. Powered by QuickLook.";
    public override string Glyph => "";
    public override string Repo => "QL-Win/QuickLook";
    public override string License => "GPL-3.0";
    protected override string WingetId => "QL-Win.QuickLook";
    protected override string ProcessName => "QuickLook";
    protected override string? ExePath => Sys.FirstExisting(@"%LocalAppData%\Programs\QuickLook\QuickLook.exe", @"%ProgramFiles%\QuickLook\QuickLook.exe");
}

public sealed class FilesApp : SimpleApp
{
    public override string Id => "files";
    public override string Name => "Files";
    public override string Description => "A modern file manager with tabs, dual pane and tags. Powered by Files.";
    public override string Glyph => "";
    public override string Repo => "files-community/Files";
    public override string License => "MIT";
    protected override string WingetId => "FilesCommunity.Files";
    protected override string ProcessName => "Files";
    protected override string StartMenuName => "Files";
    public override bool RunsInBackground => false;
}
