using System.Text;
using System.Text.Json.Nodes;

namespace Hyprism.Theming;

/// <summary>Turns a palette into each app's native theme format.</summary>
public static class Generators
{
    static readonly string[] AnsiNames = ["black", "red", "green", "yellow", "blue", "purple", "cyan", "white"];

    /// <summary>Windows Terminal "schemes" entry.</summary>
    public static JsonObject TerminalScheme(Palette p, string name = "Hyprism")
    {
        var o = new JsonObject
        {
            ["name"] = name,
            ["background"] = p.Background.Hex,
            ["foreground"] = p.Foreground.Hex,
            ["cursorColor"] = p.Accent.Hex,
            ["selectionBackground"] = p.Overlay.Hex,
        };
        for (int i = 0; i < 8; i++)
        {
            var n = AnsiNames[i];
            o[n] = p.Ansi[i].Hex;
            o["bright" + char.ToUpper(n[0]) + n[1..]] = p.Ansi[i + 8].Hex;
        }
        return o;
    }

    /// <summary>CSS custom properties used by the Zebar pack, YASB styles and the Lively slideshow.</summary>
    public static string CssVariables(Palette p)
    {
        var sb = new StringBuilder(":root {\n");
        sb.Append($"  --bg: {p.Background.Hex};\n  --bg-alpha: {p.Background.HexRgba(0xB3)};\n  --surface: {p.Surface.Hex};\n");
        sb.Append($"  --overlay: {p.Overlay.Hex};\n  --fg: {p.Foreground.Hex};\n  --muted: {p.Muted.Hex};\n");
        sb.Append($"  --accent: {p.Accent.Hex};\n  --on-accent: {p.OnAccent.Hex};\n");
        for (int i = 0; i < 16; i++) sb.Append($"  --c{i}: {p.Ansi[i].Hex};\n");
        return sb.Append("}\n").ToString();
    }

    /// <summary>Flow Launcher theme, filled from Flow's own ThemeBuilder template.</summary>
    public static string FlowLauncherTheme(Palette p, bool blur) => $$"""
        <ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                            xmlns:system="clr-namespace:System;assembly=mscorlib">
            <!-- Generated by Hyprism from palette "{{p.Name}}". Changes are overwritten. -->
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Base.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <system:Boolean x:Key="ThemeBlurEnabled">{{blur}}</system:Boolean>
            <system:String x:Key="SystemBG">{{(p.IsDark ? "Dark" : "Light")}}</system:String>
            <Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">
                <Setter Property="Background" Value="Transparent" />
                <Setter Property="Foreground" Value="{{p.Foreground.Hex}}" />
                <Setter Property="CaretBrush" Value="{{p.Accent.Hex}}" />
            </Style>
            <Style x:Key="WindowBorderStyle" BasedOn="{StaticResource BaseWindowBorderStyle}" TargetType="{x:Type Border}">
                <Setter Property="Background" Value="{{(blur ? p.Background.HexA(0x99) : p.Background.Hex)}}" />
                <Setter Property="CornerRadius" Value="10" />
                <Setter Property="BorderBrush" Value="{{p.Overlay.Hex}}" />
                <Setter Property="BorderThickness" Value="1" />
            </Style>
            <Style x:Key="WindowStyle" TargetType="{x:Type Window}" BasedOn="{StaticResource BaseWindowStyle}">
                <Setter Property="Width" Value="620" />
            </Style>
            <Style x:Key="PendingLineStyle" BasedOn="{StaticResource BasePendingLineStyle}" TargetType="{x:Type Line}">
                <Setter Property="Stroke" Value="{{p.Accent.Hex}}" />
            </Style>
            <Style x:Key="ItemTitleStyle" BasedOn="{StaticResource BaseItemTitleStyle}" TargetType="{x:Type TextBlock}">
                <Setter Property="Foreground" Value="{{p.Foreground.Hex}}" />
            </Style>
            <Style x:Key="ItemSubTitleStyle" BasedOn="{StaticResource BaseItemSubTitleStyle}" TargetType="{x:Type TextBlock}">
                <Setter Property="Foreground" Value="{{p.Muted.Hex}}" />
            </Style>
            <Style x:Key="ItemTitleSelectedStyle" BasedOn="{StaticResource BaseItemTitleSelectedStyle}" TargetType="{x:Type TextBlock}">
                <Setter Property="Foreground" Value="{{p.OnAccent.Hex}}" />
            </Style>
            <Style x:Key="ItemSubTitleSelectedStyle" BasedOn="{StaticResource BaseItemSubTitleSelectedStyle}" TargetType="{x:Type TextBlock}">
                <Setter Property="Foreground" Value="{{p.OnAccent.Hex}}" />
            </Style>
            <Color x:Key="ItemSelectedBackgroundColor">{{p.Accent.Hex}}</Color>
            <Style x:Key="ThumbStyle" BasedOn="{StaticResource BaseThumbStyle}" TargetType="{x:Type Thumb}" />
            <Style x:Key="ScrollBarStyle" BasedOn="{StaticResource BaseScrollBarStyle}" TargetType="{x:Type ScrollBar}" />
        </ResourceDictionary>
        """;
}
